<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Templates\**\*" />
        <EmbeddedResource Include="ManiaScripts\**" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Templates\**\*" />
        <None Remove="ManiaScripts\**\*" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
        <PackageReference Include="Mono.TextTemplating" Version="3.0.0" />
    </ItemGroup>

</Project>
